database:
  port: 3306
  host: "k11d205.p.ssafy.io"
  user: "kiwi"
  password: "wiki"
  database: "kiwi"

elk:
  port: 9300
  host: "k11d205.p.ssafy.io"
  user: "elastic"
  password: "elastic_kiwi"

llama:
  url: "https://98c6-34-75-59-52.ngrok-free.app"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
